In [25]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

# download data set: https://drive.google.com/file/d/13nw-uRXPY8XIZQxKRNZ3yYlho-CYm_Qt/view
# info: https://archive.ics.uci.edu/ml/datasets/banknote+authentication

# load data
bankdata = pd.read_csv("/Users/archana/Desktop/cmpe255-spring19-lab7/bill_authentication.csv")

In [26]:
# see the data
bankdata.shape

(1372, 5)

In [27]:

# see head
bankdata.head()

Variance  Skewness  Curtosis  Entropy  Class
0   3.62160    8.6661   -2.8073 -0.44699      0
1   4.54590    8.1674   -2.4586 -1.46210      0
2   3.86600   -2.6383    1.9242  0.10645      0
3   3.45660    9.5228   -4.0112 -3.59440      0
4   0.32924   -4.4552    4.5718 -0.98880      0

In [28]:

# data processing
X = bankdata.drop('Class', axis=1)  
y = bankdata['Class']

In [29]:
from sklearn.model_selection import train_test_split  
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.20)

In [30]:
# train the SVM
from sklearn.svm import SVC  
svclassifier = SVC(kernel='linear')  
svclassifier.fit(X_train, y_train)


SVC(C=1.0, cache_size=200, class_weight=None, coef0=0.0,
  decision_function_shape='ovr', degree=3, gamma='auto_deprecated',
  kernel='linear', max_iter=-1, probability=False, random_state=None,
  shrinking=True, tol=0.001, verbose=False)

In [31]:
# predictions
y_pred = svclassifier.predict(X_test)

In [32]:

# Evaluate model
from sklearn.metrics import classification_report, confusion_matrix  
print('Confusion Matrix of Linear Kernel')
print(confusion_matrix(y_test,y_pred))
print('Classification Report of Linear Kernel')
print(classification_report(y_test,y_pred))

Confusion Matrix of Linear Kernel
[[145   2]
 [  1 127]]
Classification Report of Linear Kernel
              precision    recall  f1-score   support

           0       0.99      0.99      0.99       147
           1       0.98      0.99      0.99       128

   micro avg       0.99      0.99      0.99       275
   macro avg       0.99      0.99      0.99       275
weighted avg       0.99      0.99      0.99       275



In [33]:
def import_iris():
    url = "https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data"

    # Assign colum names to the dataset
    colnames = ['sepal-length', 'sepal-width', 'petal-length', 'petal-width', 'Class']

    # Read dataset to pandas dataframe
    irisdata = pd.read_csv(url, names=colnames) 

    # process
    X = irisdata.drop('Class', axis=1)  
    y = irisdata['Class']  

    # train
    from sklearn.model_selection import train_test_split  
    X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.20)
   

In [34]:
def polynomial_kernel():
    # TODO
    # NOTE: use 8-degree in the degree hyperparameter. 
    # Trains, predicts and evaluates the model
    from sklearn.svm import SVC 
    svclassifier = SVC(kernel='poly', degree=8)  
    svclassifier.fit(X_train, y_train) 
    # predictions
    y_pred = svclassifier.predict(X_test) 
    # Evaluate model
    from sklearn.metrics import classification_report, confusion_matrix  
    print('Confusion Matrix of Polynomial Kernel')
    print(confusion_matrix(y_test,y_pred))
    print('Classification Report of Polynomial Kernel')
    print(classification_report(y_test,y_pred))

In [35]:
def gaussian_kernel():
    # TODO
    # Trains, predicts and evaluates the model
    from sklearn.svm import SVC 
    svclassifier = SVC(kernel='rbf')  
    svclassifier.fit(X_train, y_train) 
    # predictions
    y_pred = svclassifier.predict(X_test) 
    # Evaluate model
    from sklearn.metrics import classification_report, confusion_matrix  
    print('Confusion Matrix of Gaussian Kernel')
    print(confusion_matrix(y_test,y_pred))
    print('Classification Report of Gaussian Kernel')
    print(classification_report(y_test,y_pred))

In [36]:

def sigmoid_kernel():
    # TODO
    # Trains, predicts and evaluates the model
    from sklearn.svm import SVC 
    svclassifier = SVC(kernel='sigmoid')  
    svclassifier.fit(X_train, y_train) 
    # predictions
    y_pred = svclassifier.predict(X_test) 
    # Evaluate model
    from sklearn.metrics import classification_report, confusion_matrix  
    print('Confusion Matrix of Sigmoid Kernel')
    print(confusion_matrix(y_test,y_pred))
    print('Classification Report of Sigmoid Kernel')
    print(classification_report(y_test,y_pred))

In [37]:
def test():
    import_iris()
    polynomial_kernel()
    gaussian_kernel()
    sigmoid_kernel()

In [38]:

test()

/Users/archana/anaconda3/lib/python3.7/site-packages/sklearn/svm/base.py:196: FutureWarning: The default value of gamma will change from 'auto' to 'scale' in version 0.22 to account better for unscaled features. Set gamma explicitly to 'auto' or 'scale' to avoid this warning.
  "avoid this warning.", FutureWarning)


Confusion Matrix of Polynomial Kernel
[[140   7]
 [  2 126]]
Classification Report of Polynomial Kernel
              precision    recall  f1-score   support

           0       0.99      0.95      0.97       147
           1       0.95      0.98      0.97       128

   micro avg       0.97      0.97      0.97       275
   macro avg       0.97      0.97      0.97       275
weighted avg       0.97      0.97      0.97       275

Confusion Matrix of Gaussian Kernel
[[147   0]
 [  0 128]]
Classification Report of Gaussian Kernel
              precision    recall  f1-score   support

           0       1.00      1.00      1.00       147
           1       1.00      1.00      1.00       128

   micro avg       1.00      1.00      1.00       275
   macro avg       1.00      1.00      1.00       275
weighted avg       1.00      1.00      1.00       275

Confusion Matrix of Sigmoid Kernel
[[82 65]
 [61 67]]
Classification Report of Sigmoid Kernel
              precision    recall  f1-score   su

/Users/archana/anaconda3/lib/python3.7/site-packages/sklearn/svm/base.py:196: FutureWarning: The default value of gamma will change from 'auto' to 'scale' in version 0.22 to account better for unscaled features. Set gamma explicitly to 'auto' or 'scale' to avoid this warning.
  "avoid this warning.", FutureWarning)
/Users/archana/anaconda3/lib/python3.7/site-packages/sklearn/svm/base.py:196: FutureWarning: The default value of gamma will change from 'auto' to 'scale' in version 0.22 to account better for unscaled features. Set gamma explicitly to 'auto' or 'scale' to avoid this warning.
  "avoid this warning.", FutureWarning)
